#!/usr/bin/env bash
# Installs and configures nginx with a custom X-Served-By response header

apt-get update -y
apt-get install -y nginx

echo "Holberton School" > /var/www/html/index.nginx-debian.html

sed -i '/server_name _;/a\    add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

service nginx restart
