#!/usr/bin/env bash
# Transfers a file from the client to a remote server's home directory using scp
if [ "$#" -lt 4 ]; then                      # checks arg count is less than 4
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

path_to_file="$1"
ip="$2"
username="$3"
path_to_ssh_key="$4"

scp -o StrictHostKeyChecking=no -i "$path_to_ssh_key" "$path_to_file" "$username@$ip":~/#!/usr/bin/env bash
# This script is used to transfer files from one server to another using SCP.
# Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
# Check if the correct number of arguments is provided
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

file_path="$1"
destination_ip="$2"
username="$3"
ssh_key_path="$4"

scp -i "$ssh_key_path" -o StrictHostKeyChecking=no "$file_path" "$username@$destination_ip:~"
