#!/usr/bin/env bash
# Transfers a file from the client to a remote server's home directory using scp
if [ "$#" -lt 4 ]; then                      # checks arg count is less than 4
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

path_to_file="$1"
ip="$2"
username="$3"
path_to_ssh_key="$4"

scp -i "$path_to_ssh_key" -o StrictHostKeyChecking=no "$path_to_file" "$username@$ip":~/
