#!/usr/bin/env bash
# Installs and configures nginx with a custom 404 page

apt-get update -y
apt-get install -y nginx

echo "Holberton School" > /var/www/html/index.nginx-debian.html

echo "Ceci n'est pas une page" > /var/www/html/404.html

sed -i '/server_name _;/a\    error_page 404 /404.html;' /etc/nginx/sites-available/default

service nginx restart
